apiVersion: apps/v1
kind: Deployment
metadata:
  name: korrel8r
spec:
  template:
    spec:
      containers:
        - name: korrel8r
          args: ["--panic", "--verbose", "9" ]
          imagePullPolicy: Always
