# Deploy lokistack into the openshift-logging namespace.
---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  size: 1x.extra-small
  storage:
    schemas:
    - version: v12
      effectiveDate: 2022-06-01
    secret:
      name: minio
      type: s3
  storageClassName: crc-csi-hostpath-provisioner # For CRC clusters
  tenants:
    mode: openshift-logging
