apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korrel8r-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korrel8r-view
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
