apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korrel8r-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - get
  - list
