apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: korrel8r

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: korrel8r

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- clusterrolebinding.yaml

images:
- name: quay.io/korrel8r/korrel8r
  newName: quay.io/korrel8r/korrel8r
  newTag: 0.5.11-dev1
