apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  pipelines:
    # NOTE: add 'audit' to the list for audit logs. These can be very verbose.
    - inputRefs: [application, infrastructure]
      outputRefs: [default]
