name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Cache Go packages and tools
      id: cache-compiled-go
      uses: actions/cache@v3
      with:
        path: ~/go
        key: cache-${{ runner.os }}-${{ runner.arch }}

    - name: Generate
      run: make tools generate

    - name: Test
      run: go test ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v3.4.0
