name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache Go packages and tools
      uses: actions/cache@v3
      with:
        path: ~/go
        key: cache-${{ runner.os }}-${{ runner.arch }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Build
      run: make tools all

    - name: Test
      run: go test -v ./...
