name: Publish

on:
  push:
    branches: [ "main" ]

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Cache Go Packages and Tools
        id: cache-compiled-go
        uses: actions/cache@v3
        with:
          path: ~/go
          key: cache-${{ runner.os }}-${{ runner.arch }}

      - name: Generate Web Site
        run: make _site

      - name: Upload web site
        uses: actions/upload-pages-artifact@v2

  deploy:
    needs: docs
    runs-on: ubuntu-latest

    permissions:            # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      pages: write          # to deploy to Pages
      id-token: write       # to verify the deployment originates from an appropriate source

    environment:            # Deploy to the github-pages environment
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

